apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sreedharsysad/gitops-demo.git
    targetRevision: main
    path: apps/nginx/overlays/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

